import { Cl } from "@stacks/transactions";
import * as crypto from "crypto";
const moveVal = Cl.uint(1);
const saltStr = "super-secret-salt-1";
const saltBuf = new Uint8Array(32);
const saltBytes = new TextEncoder().encode(saltStr);
saltBuf.set(saltBytes.slice(0, 32));
const saltVal = Cl.buffer(saltBuf);
const tuple = Cl.tuple({ move: moveVal, salt: saltVal });
const serialized = Cl.serialize(tuple);
const hash = crypto.createHash('sha256');
hash.update(serialized);
console.log(Buffer.from(new Uint8Array(hash.digest())).toString('hex'));
